### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ilyassatlassi** [ilyassatlassi/Recipes#9]
### Hello Reviewer, 👋 

We are a group of two programmers, @BB-Simon  and @ilyassatlassi, Looking forward to coding a unique Recipe App.

We have made a Kanban board to fairly divide tasks among ourselves. Below is the link of that project.

https://github.com/users/ilyassatlassi/projects/2

**Comment by julie-ify** [comment]
Hi @ilyassatlassi and @BB-Simon,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* I cannot find your project using the link you provided. Kindly look into that.

  ![image](https://github.com/ilyassatlassi/Recipes/assets/81468675/429535c6-10a4-473a-818c-9b55018141fa)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Abenezer-Tilahun** [comment]
Hi  @ilyassatlassi @BB-Simon 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻



✔️ Good job for provide the information  about the number of people in their group
✔️ Good Job for provide link to their GitHub project
✔️ Good job for implementing RoR group project: set up your Kanban board.

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
